[package]
name = "urlf"
version = "0.1.0"
edition = "2021"

[dependencies]
gitlab = "0.1503"
clap = { version = "3", features = ["derive","cargo"] }
xdg = "2"
serde = { version = "1", features = ["derive"] } 
serde_json = "1"
toml = "0.5"
regex = "1"
confy = "0.5"